name: Upload to GCP Bucket

on:
  push:
    branches:
    - main

env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}

  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup - gcloud / gsutil
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        project_id: ${{ secrets.GCS_PROJECT }}
        export_default_credentials: true
    - name: Deploy
      run: |-
        gsutil ls
        gsutil -m rsync -R demo/ gs://$GCS_BUCKET/demo/

